name: Demo upStream Test
on: [push ,pull_request]
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3.5.2
       - name: Run Cypress tests
         uses: cypress-io/github-action@v4.1.0
         with:
          start: npm run
