name: Demo upStream Test
on: [pull_request]
jobs:
 cypress-test-upstream-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress.io
        uses: cypress-io/github-action@v2
        with:
          start: npm start
      
